version: 1
services:
  - type: web
    name: mbtiChat_Front
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      NODE_ENV: production
    nodeVersion: 14.x  # 원하는 Node.js 버전으로 설정
